{
  "sksl": {
    "entrypoint": "glitch_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 iResolution;\nuniform float iTime;\nuniform vec2 uScanLineJitter;\nuniform vec2 uVerticalJump;\nuniform float uHorizontalShake;\nuniform vec2 uColorDrift;\nuniform shader uTexture;\nuniform half2 uTexture_size;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nfloat FLT_flutter_local_nrand(float x, float y)\n{\n    return fract(sin(dot(vec2(x, y), vec2(12.98980045318603515625, 78.233001708984375))) * 43758.546875);\n}\n\nvoid FLT_main()\n{\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    vec2 uv = fragCoord / iResolution;\n    float u = uv.x;\n    float v = uv.y;\n    float param = v;\n    float param_1 = iTime;\n    float jitter = (FLT_flutter_local_nrand(param, param_1) * 2.0) - 1.0;\n    jitter *= (step(uScanLineJitter.y, abs(jitter)) * uScanLineJitter.x);\n    float jump = mix(v, fract(v + uVerticalJump.y), uVerticalJump.x);\n    float param_2 = iTime;\n    float param_3 = 2.0;\n    float shake = (FLT_flutter_local_nrand(param_2, param_3) - 0.5) * uHorizontalShake;\n    float drift = sin(jump + uColorDrift.y) * uColorDrift.x;\n    vec4 src1 = uTexture.eval(uTexture_size * ( fract(vec2((u + jitter) + shake, jump))));\n    vec4 src2 = uTexture.eval(uTexture_size * ( fract(vec2(((u + jitter) + shake) + drift, jump))));\n    float a = (src1.w + src2.w) * 0.5;\n    fragColor = vec4(src1.x, src2.y, src1.z, a);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "iResolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "iTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 2,
        "name": "uTexture",
        "rows": 1,
        "type": 12
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uScanLineJitter",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 4,
        "name": "uVerticalJump",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 5,
        "name": "uHorizontalShake",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 6,
        "name": "uColorDrift",
        "rows": 2,
        "type": 10
      }
    ]
  }
}